
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.BookController;
import controller.BorrowerController;
import controller.ValidationController;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import model.Book;
import model.Borrower;

/**
 *
 * @author olwia
 */
public class BooksManager extends javax.swing.JPanel {

    /**
     * Creates new form BooksManager
     */
    public BooksManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableBook = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton BtnAdd = new javax.swing.JButton();
        BtnMain = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        tfBookID = new javax.swing.JTextField();
        tfBookISBNCode = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        tfBookTitle = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        tfBookGenre = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        tfBookReturnedDate = new javax.swing.JTextField();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        tfBookLastBorrowedDate = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        tfBorrowerID = new javax.swing.JTextField();
        javax.swing.JButton BtnView = new javax.swing.JButton();
        cbxAvailable = new javax.swing.JCheckBox();
        BtnSearch = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1025, 740));

        TableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Genre", "ISBN Code", "Booked Out", "LBD", "Date Returned", "Borrower ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBook);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Books");

        BtnAdd.setBackground(new java.awt.Color(110, 83, 83));
        BtnAdd.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Add");
        BtnAdd.setBorder(null);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnMain.setBackground(new java.awt.Color(110, 83, 83));
        BtnMain.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnMain.setForeground(new java.awt.Color(255, 255, 255));
        BtnMain.setText("Main Menu");
        BtnMain.setBorder(null);
        BtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMainActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID:");

        tfBookID.setToolTipText("Enter ID");

        tfBookISBNCode.setToolTipText("Enter ISBN code");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Title:");

        tfBookTitle.setToolTipText("Enter book title");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ISBN Code:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Genre:");

        tfBookGenre.setToolTipText("Enter book genre");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Returned Date:");

        tfBookReturnedDate.setToolTipText("Enter returned date");
        tfBookReturnedDate.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Availability:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Borrower ID:");

        tfBookLastBorrowedDate.setToolTipText("Enter last borrowed date");
        tfBookLastBorrowedDate.setEnabled(false);
        tfBookLastBorrowedDate.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Last Borrowed Date:");

        tfBorrowerID.setToolTipText("Enter Borrower ID");
        tfBorrowerID.setName(""); // NOI18N

        BtnView.setBackground(new java.awt.Color(110, 83, 83));
        BtnView.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnView.setForeground(new java.awt.Color(255, 255, 255));
        BtnView.setText("View All");
        BtnView.setBorder(null);
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        cbxAvailable.setText("IS BOOKED OUT?");
        cbxAvailable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxAvailableMouseClicked(evt);
            }
        });

        BtnSearch.setBackground(new java.awt.Color(110, 83, 83));
        BtnSearch.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Search ID");
        BtnSearch.setBorder(null);
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(110, 83, 83));
        BtnUpdate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(null);
        BtnUpdate.setEnabled(false);
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(110, 83, 83));
        BtnDelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.setBorder(null);
        BtnDelete.setEnabled(false);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnReset.setBackground(new java.awt.Color(110, 83, 83));
        BtnReset.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnReset.setForeground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("Reset");
        BtnReset.setBorder(null);
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(352, 352, 352)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(50, 50, 50))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(140, 140, 140)))
                                            .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfBookLastBorrowedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfBookReturnedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfBookGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfBookISBNCode, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfBookISBNCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBookGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(4, 4, 4)
                                        .addComponent(tfBookLastBorrowedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(tfBookReturnedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents
private BookController bc;
    ValidationController vc = new ValidationController();
    Book book;   
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try {
            bc = new BookController();
            vc = new ValidationController();

            int id = Integer.parseInt(tfBookID.getText().trim()); // Ensure input is trimmed to avoid NumberFormatException           
            String title = tfBookTitle.getText().trim();    // Getting text input directly for title, genre, and ISBN
            String genre = tfBookGenre.getText().trim();
            String isbn = tfBookISBNCode.getText().trim();            
            boolean isNotAvailable = cbxAvailable.isSelected(); // Getting boolean value from JCheckBox

            Date LBD = null;
            Date RD = null;
            int borrowerID = 0;
           
            if (isNotAvailable) { // Check if the book is checked out                    
                String lastBorrowedDateText = tfBookLastBorrowedDate.getText().trim();  // Parsing dates with proper format
                String returnedDateText = tfBookReturnedDate.getText().trim();

                if (!lastBorrowedDateText.isEmpty() && !returnedDateText.isEmpty()) {
                    try {
                        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                        LBD = formatter.parse(lastBorrowedDateText);
                        RD = formatter.parse(returnedDateText);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Error: Date format should be yyyy-MM-dd", "Validation Error", JOptionPane.ERROR_MESSAGE);
                        return; // Exit if date parsing fails
                    }
                }
                
                try {   // Parsing borrower ID as integer
                    if (tfBorrowerID.getText().isBlank()){
                        borrowerID = 0;
                    } else {
                      borrowerID = Integer.parseInt(tfBorrowerID.getText().trim()); 
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Error: Invalid borrower ID", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return; // Exit if borrower ID parsing fails
                }
            }
           
            book = new Book(id, title, genre, isbn, isNotAvailable, LBD, RD, borrowerID);  // Create new Book object
           
            ValidationController.ValidationResult result = vc.validateBook(book);   // Validate book using ValidationController

            if (result.isValid()) {
                if (isNotAvailable || borrowerID == 0 || borrowerExists(borrowerID)) { 
                    if (!bookExists(book.getId())) { 
                      bc.addBook(book);   // Add book to the database                   
                        populateTable(false, true); // Pull and update the table from DB
                        JOptionPane.showMessageDialog(null, "Book " + book.getId() + " successfully added!");
                        clearFields();  
                    } else {
                       JOptionPane.showMessageDialog(null, "Error: Book " + book.getId() + " already exists", "Validation Error", JOptionPane.ERROR_MESSAGE); 
                       return;
                    }                   
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Borrower " + borrowerID + " does not exist", "Validation Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {               
                JOptionPane.showMessageDialog(null, "Error: " + result.getIdentifier(), "Validation Error", JOptionPane.ERROR_MESSAGE); // Display error dialog with the validation result
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Invalid input for numeric fields", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Print stack trace for debugging purposes
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMainActionPerformed
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        } else {
            System.out.println("No parent frame found.");
        }
        MainDashboard md = new MainDashboard();
        md.setVisible(true);
    }//GEN-LAST:event_BtnMainActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        populateTable(false, false);
    }//GEN-LAST:event_BtnViewActionPerformed

    private void TableBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBookMouseClicked
        int selectedRow = TableBook.getSelectedRow();   // Check if a row is selected

        if (selectedRow != -1) {           
            Object idValue = TableBook.getValueAt(selectedRow, 0);  // Get values from the selected row
            Object titleValue = TableBook.getValueAt(selectedRow, 1);
            Object genreValue = TableBook.getValueAt(selectedRow, 2);
            Object isbnValue = TableBook.getValueAt(selectedRow, 3);
            Object availabilityValue = TableBook.getValueAt(selectedRow, 4);
            Object lastBorrowedDateValue = TableBook.getValueAt(selectedRow, 5);
            Object returnedDateValue = TableBook.getValueAt(selectedRow, 6);
            Object borrowerIDValue = TableBook.getValueAt(selectedRow, 7);
           
            String id = idValue != null ? idValue.toString() : "";  // Convert to String, defaulting to empty string if null
            String title = titleValue != null ? titleValue.toString() : "";
            String genre = genreValue != null ? genreValue.toString() : "";
            String isbn = isbnValue != null ? isbnValue.toString() : "";
            String availability = availabilityValue != null ? availabilityValue.toString() : "";
            String lastBorrowedDate = lastBorrowedDateValue != null ? lastBorrowedDateValue.toString() : "";
            String returnedDate = returnedDateValue != null ? returnedDateValue.toString() : "";
            String borrowerID = borrowerIDValue != null ? borrowerIDValue.toString() : "";
           
            tfBookID.setText(id);   // Set the values in text fields
            tfBookTitle.setText(title);
            tfBookGenre.setText(genre);
            tfBookISBNCode.setText(isbn);
            tfBookLastBorrowedDate.setText(lastBorrowedDate);
            tfBookReturnedDate.setText(returnedDate);
            tfBorrowerID.setText(borrowerID);            
            cbxAvailable.setSelected(Boolean.parseBoolean(availability));   // Set checkbox state
            
            tfBookID.setEnabled(false); // Disable the ID field (not editable) and enable update and delete buttons
            if (cbxAvailable.isSelected()){
                tfBookLastBorrowedDate.setEnabled(true);
                tfBookReturnedDate.setEnabled(true);
            } else {
                tfBookLastBorrowedDate.setEnabled(false);
                tfBookReturnedDate.setEnabled(false);
            }              
            BtnUpdate.setEnabled(true);
            BtnDelete.setEnabled(true);
        } else {           
            clearFields();  // No row is selected, clear fields and disable buttons
            tfBookID.setEnabled(true);
            BtnUpdate.setEnabled(false);
            BtnDelete.setEnabled(false);
        }
    }//GEN-LAST:event_TableBookMouseClicked

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        populateTable(true, false);
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try {
            bc = new BookController();
            vc = new ValidationController();
            
            int id = Integer.parseInt(tfBookID.getText().trim());   // Parse and validate input fields
            String title = tfBookTitle.getText().trim();
            String genre = tfBookGenre.getText().trim();
            String isbn = tfBookISBNCode.getText().trim();
            boolean isNotAvailable = cbxAvailable.isSelected(); // Directly gets the boolean value

            Date lastBorrowedDate = null;
            Date returnedDate = null;
            String lastBorrowedDateText = tfBookLastBorrowedDate.getText().trim();
            String returnedDateText = tfBookReturnedDate.getText().trim();
            int borrowerID = 0;
            
            if (isNotAvailable) {  // Check if the book is being borrowed
                if (!lastBorrowedDateText.isEmpty()) {
                    try {
                        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                        lastBorrowedDate = formatter.parse(lastBorrowedDateText);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Error: Date format should be yyyy-MM-dd", "Validation Error", JOptionPane.ERROR_MESSAGE);
                        return; // Exit if date parsing fails
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Last Borrowed Date is required when the book is being borrowed.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return; // Exit if last borrowed date is empty
                }

                if (!returnedDateText.isEmpty()) {
                    try {
                        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                        returnedDate = formatter.parse(returnedDateText);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Error: Date format should be yyyy-MM-dd", "Validation Error", JOptionPane.ERROR_MESSAGE);
                        return; // Exit if date parsing fails
                    }
                }
               
                String borrowerIDText = tfBorrowerID.getText().trim();  // Parse borrower ID as integer if it is not empty
                if (!borrowerIDText.isEmpty()) {
                    try {
                        borrowerID = Integer.parseInt(borrowerIDText);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Error: Invalid borrower ID", "Validation Error", JOptionPane.ERROR_MESSAGE);
                        return; // Exit if borrower ID parsing fails
                    }
                }
            }
            
            book = new Book(id, title, genre, isbn, isNotAvailable, lastBorrowedDate, returnedDate, borrowerID);   // Create a Book object
           
            ValidationController.ValidationResult result = vc.validateBook(book);   // Validate book using ValidationController
            if (result.isValid()) {
                if (isNotAvailable && borrowerID == 0 || borrowerExists(borrowerID)) {                  
                bc.updateBook(book);    // Update book in the database               
                populateTable(false, true); // Pull and update the table from DB
                JOptionPane.showMessageDialog(null, "Book " + book.getId() + " successfully updated!");                
                clearFields();  // Clear fields
                } else {
                   JOptionPane.showMessageDialog(null, "Error: Borrower " + borrowerID + " does not exist", "Validation Error", JOptionPane.ERROR_MESSAGE); 
                }               
            } else {                
                JOptionPane.showMessageDialog(null, "Error: " + result.getIdentifier(), "Validation Error", JOptionPane.ERROR_MESSAGE); // Display error dialog with the validation result
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Invalid number format. Please check your input.", "Format Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        try {
            bc = new BookController();          
            int id = Integer.parseInt(tfBookID.getText().trim());   // Parse input field           
            book = new Book(id, "", "", "", true, null, null, 0);   // Create a Book object with only ID (other fields are irrelevant for delete)           
            bc.deleteBook(book);    // Delete book from the database            
            populateTable(false, true); // Pull and update the table from DB
            JOptionPane.showMessageDialog(null, "Book " + book.getId() + " successfully deleted!");          
            clearFields();  // Clear fields
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Invalid number format. Please check your input.", "Format Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        clearFields();
        tfBookID.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
        TableBook.clearSelection();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void cbxAvailableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxAvailableMouseClicked
        if (cbxAvailable.isSelected()){
            tfBookLastBorrowedDate.setEnabled(true);
            tfBookReturnedDate.setEnabled(true); 
        } else {
            tfBookLastBorrowedDate.setEnabled(false);
            tfBookReturnedDate.setEnabled(false); 
        }    
    }//GEN-LAST:event_cbxAvailableMouseClicked

    private void populateTable(boolean search, boolean update) {
        try {
            bc = new BookController();
            DefaultTableModel model = (DefaultTableModel) TableBook.getModel();
            if (search) {               
                bc.viewAllBooks(tfBookID.getText());    // Perform search
            } else {               
                bc.viewAllBooks("");    // Retrieve all books
            }

            List<Book> books = bc.getBooks();            
            model.setRowCount(0);   // Clear existing rows

            if (books.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No books found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {                
                for (Book book : books) {   // Populate the table with new data
                    Object[] row = { book.getId(), book.getTitle(), book.getGenre(), book.getIsbn(), book.isAvailable(), book.getLastBorrowed(), book.getDateReturned(), book.getBorrowerID() };
                    model.addRow(row);
                }
                if (!update) {
                    JOptionPane.showMessageDialog(null, "Books table successfully pulled!");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Book table not pulled!", "Read Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }
    
    private void clearFields() {
        tfBookID.setText("");
        tfBookTitle.setText("");
        tfBookGenre.setText("");
        tfBookISBNCode.setText("");
        cbxAvailable.setSelected(false); // Changed to checkbox
        tfBookLastBorrowedDate.setEnabled(false);
        tfBookReturnedDate.setEnabled(false); 
        tfBookLastBorrowedDate.setText("");
        tfBookReturnedDate.setText("");
        tfBorrowerID.setText("");
    }
    
    private boolean borrowerExists(int borrowerID) {
        try {
            BorrowerController bc = new BorrowerController();            
            bc.viewAllBorrowers("");    // Retrieve all borrowers            
            List<Borrower> borrowers = bc.getBorrowers();   // Get the list of all borrowers            
            for (Borrower borrower : borrowers) {   // Check if any borrower's ID matches the provided borrowerID
                if (borrower.getId() == borrowerID) {
                    return true; // Borrower ID found
                }
            }           
            return false;   // No matching borrower ID found
        } catch (Exception ex) {           
            ex.printStackTrace();   // Print exception to the console and return false
            return false;
        }
    }
    
    private boolean bookExists(int bookID) {
        try {
            bc.viewAllBooks("");
            List<Book> books = bc.getBooks();
            for (Book book : books){
                if (book.getId() == bookID) {
                    return true;
                }
            }
            return false;    
        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnMain;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TableBook;
    private javax.swing.JCheckBox cbxAvailable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBookGenre;
    private javax.swing.JTextField tfBookID;
    private javax.swing.JTextField tfBookISBNCode;
    private javax.swing.JTextField tfBookLastBorrowedDate;
    private javax.swing.JTextField tfBookReturnedDate;
    private javax.swing.JTextField tfBookTitle;
    private javax.swing.JTextField tfBorrowerID;
    // End of variables declaration//GEN-END:variables
}
