
package view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.BorrowerController;
import controller.ValidationController;
import java.util.List;
import model.Borrower;

/**
 *
 * @author olwia
 */
public class BorrowerManager extends javax.swing.JPanel {

    /**
     * Creates new form BorrowerManager
     */
    public BorrowerManager() {
        initComponents();
        populateTable(false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBorrowerID = new javax.swing.JTextField();
        tfBorrowerName = new javax.swing.JTextField();
        tfBorrowerLastName = new javax.swing.JTextField();
        tfBorrowerPhoneNumber = new javax.swing.JTextField();
        tfBorrowerEmailAddress = new javax.swing.JTextField();
        tfBorrowerHomeAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBorrowers = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JButton BtnAdd = new javax.swing.JButton();
        javax.swing.JButton BtnView = new javax.swing.JButton();
        BtnMain = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        BtnSearch = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1025, 760));

        tfBorrowerID.setToolTipText("Enter ID");

        tfBorrowerName.setToolTipText("Enter your Name");

        tfBorrowerLastName.setToolTipText("Enter your Last Name");

        tfBorrowerPhoneNumber.setToolTipText("Enter your Phone Number");

        tfBorrowerEmailAddress.setToolTipText("Enter Email Address");

        tfBorrowerHomeAddress.setToolTipText("Enter Home Address");

        TableBorrowers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last Name", "Phone Number", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableBorrowers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBorrowersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBorrowers);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Borrowers");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID:");

        BtnAdd.setBackground(new java.awt.Color(110, 83, 83));
        BtnAdd.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Add");
        BtnAdd.setBorder(null);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnView.setBackground(new java.awt.Color(110, 83, 83));
        BtnView.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnView.setForeground(new java.awt.Color(255, 255, 255));
        BtnView.setText("View All");
        BtnView.setBorder(null);
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        BtnMain.setBackground(new java.awt.Color(110, 83, 83));
        BtnMain.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnMain.setForeground(new java.awt.Color(255, 255, 255));
        BtnMain.setText("Main Menu");
        BtnMain.setBorder(null);
        BtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMainActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Phone Number:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Home Address:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Email Address:");

        BtnSearch.setBackground(new java.awt.Color(110, 83, 83));
        BtnSearch.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        BtnSearch.setText("Search ID");
        BtnSearch.setBorder(null);

        BtnUpdate.setBackground(new java.awt.Color(110, 83, 83));
        BtnUpdate.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(null);
        BtnUpdate.setEnabled(false);
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(110, 83, 83));
        BtnDelete.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.setBorder(null);
        BtnDelete.setEnabled(false);
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnReset.setBackground(new java.awt.Color(110, 83, 83));
        BtnReset.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnReset.setForeground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("Reset");
        BtnReset.setBorder(null);
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfBorrowerName)
                                                .addGap(41, 41, 41)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfBorrowerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfBorrowerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfBorrowerHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfBorrowerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(tfBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(tfBorrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBorrowerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBorrowerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBorrowerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBorrowerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBorrowerHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnAdd.getAccessibleContext().setAccessibleName("");
        BtnUpdate.getAccessibleContext().setAccessibleName("");
        BtnDelete.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private BorrowerController bc;
    ValidationController vc = new ValidationController();
    Borrower borrower;

    private void populateTable(boolean search, boolean update) {
        try {
            bc = new BorrowerController();
            DefaultTableModel model = (DefaultTableModel) TableBorrowers.getModel();

            if (search) {               
                bc.viewAllBorrowers(tfBorrowerID.getText());    // Perform search
            } else {               
                bc.viewAllBorrowers("");    // Retrieve all authors
            }

            List<Borrower> borrowers = bc.getBorrowers();            
            model.setRowCount(0);   // Clear existing rows

            if (borrowers.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No borrowers found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {               
                for (Borrower borrower : borrowers) {   // Populate the table with new data
                    Object[] row = {borrower.getId(), borrower.getName(), borrower.getSurname(), borrower.getPhone(), borrower.getEmail(), borrower.getAddress()};
                    model.addRow(row);
                }
                if (!update) {
                    JOptionPane.showMessageDialog(null, "Borrower table successfully pulled!");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Borrower table not pulled!", "Read Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try {
            bc = new BorrowerController();

            int id = Integer.parseInt(tfBorrowerID.getText());
            String name = tfBorrowerName.getText();
            String lastName = tfBorrowerLastName.getText();
            String phoneNumber = tfBorrowerPhoneNumber.getText();
            String email = tfBorrowerEmailAddress.getText();
            String address = tfBorrowerHomeAddress.getText();

            borrower = new Borrower(id, name, lastName, phoneNumber, email, address);            
            ValidationController.ValidationResult result = vc.validateBorrower(borrower);   // Validate Borrower

            if (result.isValid()) { 
                if (!borrowerExists(borrower.getId())){
                   bc.addBorrower(borrower);   // Add author to the database               
                    populateTable(false, true); //Pull and Update the table from DB
                    JOptionPane.showMessageDialog(null, "Borrower " + Integer.toString(borrower.getId()) + " successfully added!");                                
                    clearFields();   //Clear all fields: 
                } else {
                    JOptionPane.showMessageDialog(null, "Error: Borrower " + borrower.getId() + " already exists", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }                              
            } else {                
                JOptionPane.showMessageDialog(null, "Error: " + result.getIdentifier(), "Validation Error", JOptionPane.ERROR_MESSAGE); // Display error dialog with the identifier result
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
       populateTable(false,false);
    }//GEN-LAST:event_BtnViewActionPerformed

    private void BtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMainActionPerformed
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        } else {
            System.out.println("No parent frame found.");
        }
        MainDashboard md = new MainDashboard();
        md.setVisible(true);
    }//GEN-LAST:event_BtnMainActionPerformed

    private void TableBorrowersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBorrowersMouseClicked
        int selectedRow = TableBorrowers.getSelectedRow();  // Check if a row is selected

        if (selectedRow != -1) {            
            Object idValue = TableBorrowers.getValueAt(selectedRow, 0); // Get values from the selected row
            Object nameValue = TableBorrowers.getValueAt(selectedRow, 1);
            Object surnameValue = TableBorrowers.getValueAt(selectedRow, 2);
            Object phoneValue = TableBorrowers.getValueAt(selectedRow, 3);
            Object emailValue = TableBorrowers.getValueAt(selectedRow, 4);
            Object addressValue = TableBorrowers.getValueAt(selectedRow, 5);
            
            String id = idValue != null ? idValue.toString() : "";  // Convert to String, defaulting to empty string if null
            String name = nameValue != null ? nameValue.toString() : "";
            String surname = surnameValue != null ? surnameValue.toString() : "";
            String phone = phoneValue != null ? phoneValue.toString() : "";
            String email = emailValue != null ? emailValue.toString() : "";
            String address = addressValue != null ? addressValue.toString() : "";
            
            tfBorrowerID.setText(id);   // Set the values in text fields
            tfBorrowerName.setText(name);
            tfBorrowerLastName.setText(surname);
            tfBorrowerPhoneNumber.setText(phone);
            tfBorrowerEmailAddress.setText(email);
            tfBorrowerHomeAddress.setText(address);
          
            tfBorrowerID.setEnabled(false); // Disable the ID field and enable buttons
            BtnUpdate.setEnabled(true);
            BtnDelete.setEnabled(true);
        }
    }//GEN-LAST:event_TableBorrowersMouseClicked

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try {
            bc = new BorrowerController();

            int id = Integer.parseInt(tfBorrowerID.getText());
            String name = tfBorrowerName.getText();
            String lastName = tfBorrowerLastName.getText();
            String phoneNumber = tfBorrowerPhoneNumber.getText();
            String email = tfBorrowerEmailAddress.getText();
            String address = tfBorrowerHomeAddress.getText();

            borrower = new Borrower(id, name, lastName, phoneNumber, email, address);            
            ValidationController.ValidationResult result = vc.validateBorrower(borrower);   // Validate 

            if (result.isValid()) {               
                bc.updateBorrower(borrower);    // Add borrower to the database               
                populateTable(false,true);  //Pull and Update the table from DB
                JOptionPane.showMessageDialog(null, "Borrower " + Integer.toString(borrower.getId()) + " successfully updated!");
            } else {               
                JOptionPane.showMessageDialog(null, "Error: " + result.getIdentifier(), "Validation Error", JOptionPane.ERROR_MESSAGE); // Display error dialog with the identifier result
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        try {
            bc = new BorrowerController();

            int id = Integer.parseInt(tfBorrowerID.getText());
            String name = tfBorrowerName.getText();
            String lastName = tfBorrowerLastName.getText();
            String phoneNumber = tfBorrowerPhoneNumber.getText();
            String email = tfBorrowerEmailAddress.getText();
            String address = tfBorrowerHomeAddress.getText();

            borrower = new Borrower(id, name, lastName, phoneNumber, email, address);           
            ValidationController.ValidationResult result = vc.validateBorrower(borrower);   // Validate Author

            if (result.isValid()) {                
                bc.deleteBorrower(borrower);  // Add author to the database              
                populateTable(false,true);  //Pull and Update the table from DB
                JOptionPane.showMessageDialog(null, "Borrower " + Integer.toString(borrower.getId()) + " successfully deleted!");
            } else {               
                JOptionPane.showMessageDialog(null, "Error: " + result.getIdentifier(), "Validation Error", JOptionPane.ERROR_MESSAGE); // Display error dialog with the identifier result
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        clearFields();      
        tfBorrowerID.setEnabled(true);  // Re-enable the ID text field for new entries       
        BtnUpdate.setEnabled(false);    // Disable the update and delete buttons
        BtnDelete.setEnabled(false);       
        TableBorrowers.clearSelection();    // Deselect any selected row in the table
    }//GEN-LAST:event_BtnResetActionPerformed

    private void clearFields(){
        tfBorrowerID.setText("");   // Clear all text fields
        tfBorrowerName.setText("");
        tfBorrowerLastName.setText("");
        tfBorrowerPhoneNumber.setText("");
        tfBorrowerEmailAddress.setText("");
        tfBorrowerHomeAddress.setText("");
    }
    
    private boolean borrowerExists(int borrowerID) {
        try {
            BorrowerController bc = new BorrowerController();            
            bc.viewAllBorrowers("");    // Retrieve all borrowers            
            List<Borrower> borrowers = bc.getBorrowers();   // Get the list of all borrowers            
            for (Borrower borrower : borrowers) {   // Check if any borrower's ID matches the provided borrowerID
                if (borrower.getId() == borrowerID) {
                    return true; // Borrower ID found
                }
            }           
            return false;   // No matching borrower ID found
        } catch (Exception ex) {           
            ex.printStackTrace();   // Print exception to the console and return false
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnMain;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TableBorrowers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBorrowerEmailAddress;
    private javax.swing.JTextField tfBorrowerHomeAddress;
    private javax.swing.JTextField tfBorrowerID;
    private javax.swing.JTextField tfBorrowerLastName;
    private javax.swing.JTextField tfBorrowerName;
    private javax.swing.JTextField tfBorrowerPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
